#!/bin/bash
#centos-main vm
virt-install --connect qemu+ssh://root@medusa-arch.raspi/system \
        --name "${VM_NAME}" \
        --location="http://centos7-main/centos7/" \
        --disk path="/root/Leon/QemuVM/rhcsa/vols/${VM_DISK}.qcow2",size=${VM_DISK_SIZE},bus=virtio,format=qcow2 \
	--memory=$VM_MEM \
        --noautoconsole \
        --graphics none \
        --os-variant "centos7.0" \
	--vcpus 2 \
	--cpu host \
	--os-type linux \
	--network network=br0,model=virtio \
        --console pty,target_type=serial \
        --extra-args "ks=http://centos7-main/centos7/anaconda-ks.cfg console=ttyS0,115200n8 serial SERVERNAME=${hostname}" \
        --wait=-1
